# Site settings
title: @Manaday
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "http://manadaym.github.io/manaday-mavani-website"
url: "http://yourdomain.com"
twitter_username: ManadayM
github_username:  ManadayM
facebook_username:  manaday.mavani

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
